// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEDAgws6xbs6YWneP4fcNTjxeFJIbOC-Q',
    appId: '1:730144185812:web:2c42a52688f3b7f85fca41',
    messagingSenderId: '730144185812',
    projectId: 'collabix-59791',
    authDomain: 'collabix-59791.firebaseapp.com',
    storageBucket: 'collabix-59791.firebasestorage.app',
    measurementId: 'G-9QS67VR0HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFAhUK_gpVhNoH2lk4Wh4dYwE3IPxMZbE',
    appId: '1:730144185812:android:cec862ea358b5ccf5fca41',
    messagingSenderId: '730144185812',
    projectId: 'collabix-59791',
    storageBucket: 'collabix-59791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsv5bQqtHJDjrj-lVVAfV4RsYkEBTW4U',
    appId: '1:730144185812:ios:2f9c71e02cc075525fca41',
    messagingSenderId: '730144185812',
    projectId: 'collabix-59791',
    storageBucket: 'collabix-59791.firebasestorage.app',
    iosBundleId: 'com.example.collabix',
  );
}
